apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: authentik

resources:
  - namespace.yaml
  - httproute.yaml
  - pvc.yaml

helmCharts:
  - name: authentik
    repo: https://charts.goauthentik.io
    version: 2024.12.3
    releaseName: authentik
    namespace: authentik
    valuesFile: values.yaml
