apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: auth
  namespace: argocd
  labels:
    dev.beans: auth
spec:
  generators:
    - git:
        repoURL: https://github.com/papapumpkin/homelarb
        revision: HEAD
        directories:
          - path: k8s/infra/auth/*
  template:
    metadata:
      name: "{{ path.basename }}"
      labels:
        dev.beans: auth
    spec:
      project: auth
      source:
        plugin:
          name: kustomize-build-with-helm
        repoURL: https://github.com/papapumpkin/homelarb
        targetRevision: HEAD
        path: "{{ path }}"
      destination:
        name: in-cluster
        namespace: argocd
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
