apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - http-route.yaml
  - oidc.yaml
  - cmp-plugin.yaml

helmCharts:
  - name: argo-cd
    repo: https://argoproj.github.io/argo-helm
    version: 7.8.2
    releaseName: "argocd"
    namespace: argocd
    valuesFile: values.yaml
