apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: gateway-cert
  namespace: gateway
spec:
  secretName: gateway-cert
  dnsNames:
    - "*.beans.lan"
  issuerRef:
    name: internal-ca
    kind: ClusterIssuer
