apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: gateway

resources:
  - namespace.yaml
  - gateway-class.yaml
  - gateway-external.yaml
  - gateway-internal.yaml
  - gateway-tls-passthrough.yaml
  - certificate.yaml

commonLabels:
  app.kubernetes.io/name: gateway
  app.kubernetes.io/part-of: network
