persistence:
  defaultClass: true
  defaultFsType: ext4

ingress:
  enabled: false
  ingressClassName: cilium
  host: longhorn.beans.lan
  tls: true
  annotations:
    cert-manager.io/cluster-issuer: internal-ca

service:
  ui:
    type: ClusterIP

defaultSettings:
  defaultReplicaCount: 3
  createDefaultDiskLabeledNodes: true
  # Adjusted CPU resources for better performance with LVM
  guaranteedEngineManagerCPU: 0.25
  guaranteedReplicaManagerCPU: 0.25
  storageMinimalAvailablePercentage: 10
  # LVM-specific settings
  storageOverProvisioningPercentage: 200
  disableSchedulingOnCordonedNode: true
  replicaZoneSoftAntiAffinity: true
  # Added LVM-specific settings
  storageReservedPercentageForDefaultDisk: 10
  autoCleanupSystemGeneratedSnapshot: true
  concurrentAutomaticEngineUpgradePerNodeLimit: 3
  defaultDataLocality: "best-effort"

  # nodes:
  #   - name: cp-01
  #     disks:
  #       - path: /var/lib/longhorn
  #         allowScheduling: true
  #   - name: cp-02
  #     disks:
  #       - path: /var/lib/longhorn
  #         allowScheduling: true
  #   - name: cp-03
  #     disks:
  #       - path: /var/lib/longhorn
  #         allowScheduling: true
  #   - name: worker-01
  #     disks:
  #       - path: /var/lib/longhorn
  #         allowScheduling: true
  #   - name: worker-02
  #     disks:
  #       - path: /var/lib/longhorn
  #         allowScheduling: true
  #   - name: worker-03
  #     disks:
  #       - path: /var/lib/longhorn
  #         allowScheduling: true
