apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - cluster-issuer.yaml

helmCharts:
  - name: cert-manager
    releaseName: cert-manager
    version: v1.15.2
    repo: https://charts.jetstack.io
    valuesFile: values.yaml
    includeCRDs: true
    namespace: cert-manager
