apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: auth
  namespace: argocd
spec:
  sourceRepos:
    - "https://github.com/papapumpkin/homelarb"
  destinations:
    - namespace: "argocd"
      server: "*"
    - namespace: "cilium"
      server: "*"
    - namespace: "gateway"
      server: "*"

  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
